spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mywebsite?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zy20010520!!!
  redis:
    host: 127.0.0.1
    port: 6379
    password: Zy20010520
    database: 15
server:
  port: 20000
